apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  ENVIRONMENT: {{ .Values.environment | quote }}
  SECRET_BACKEND: {{ .Values.secretBackend | quote }}
  IMAGE_TAG: {{ .Values.image.tag | quote }}
