apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - vault.yaml          # NON-PROD secret backend (sync-wave 0)
  - secretstore.yaml    # ESO -> Vault            (sync-wave 1)
  - externalsecret.yaml # materializes web-db-credentials (sync-wave 2)
